version: 2.0
jobs:
  build:
    docker:
      - image: circleci/elixir:1.4
    working_directory: ~/erledis
    steps:
      - checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix espec
